### PR TITLE
Use time in nanoseconds for the seed to make maps random.

### PR DESCRIPTION
**Pull request by gitarzysta**

### CODE REVIEW

**Comment by Janzert** [comment]
While it may or may not have been originally, the 1 second granularity on the seed is purposeful at this point to allow some duplicate maps to occur (unfortunately a UI was never developed to expose these games on the site).

If you need to guarantee unique seeds in local testing it's recommended that you pass in explicit seeds to the engine using the -s option.

**Comment by gitarzysta** [comment]
The concern is predictability of the maps. The seeds/maps for the final day/hour of the competition are already known and the number is quite small. Please correct me if I am wrong but I do not see anything setting the seed for the game engine on the site. Using your logic if your desire is to have duplicate seeds you can do it easily by using the -s option without making the seeds trivially  predictable.

**Comment by Janzert** [comment]
Yes, it's true anyone can check the 500,000-600,000 seeds and 1 million plus maps that will potentially be used in the finals. If they can find something useful to precompute for all of them, I'm more inclined to cheer them on than to try and stop it.

Besides even coming up with something to precompute; for the precomputation to be useful it has to take longer than the 30 seconds of initialization time already available at the start of the game. So you'll have to use the equivalent of around a year of server cpu time (plus or minus ~60 days). I'm sure it's feasible, but it's not trivial. You could of course split up the computation so the final 30 seconds in done during initialization time and only the extra time needed is done beforehand but that gets even trickier (and rather riskier) to implement.

So if you have something to precompute, go, go, go. But I would suggest that you test it pretty well to make sure it's actually giving you a pretty big benefit before putting the work into getting all that computation done.

**Comment by gitarzysta** [comment]
There is also the concern about the quality of the random numbers used, something the ranking algorithm relies upon heavily. I am also still not hearing anything that would convince me restricting the number of seed values to less than 0.0025% of available space is a good idea and what purpose does it serve.

**Comment by snaar** [comment]
@Janzert - I'm against this change from logical design point of view as well, but it's been talked about before, so no need for me to rehash it. I.e. I'm with you from purity point of view.

However, maybe we should just "screw it" and push this in? It's less tedious than trying to explain it every time it's brought up. Anything this change would break from technical point of view? I'm not sure I totally follow the duplicate map thing.

**Comment by Janzert** [comment]
@gitarzysta in what way does the ranking system heavily rely on the engine random numbers? The ways that come to mind offhand I would characterize as relatively small.

@snaar There are a few spots in the backend (e.g. parsing and building replay names) that should be fine but may have the potential to break. For myself I have one local script that relies on the current seed system as a double check, it would be fairly trivial to drop the check if the change went in. For other players in general, if they've written written scripts that parse replay names poorly or mistakenly depend on fitting the seed value in a signed int may break.

Overall at this stage I'd rather not make changes that effect the backend unless they are going to have a definite positive effect for the finals.

**Comment by snaar** [comment]
All right, then let's merge it in after finals are done.

**Pull request merged**
