### PR TITLE
fixed ml parser

### PR DESCRIPTION
**Pull request by djbyrne**
Was unable to parse .hlt replay files. 

The parser worked after applying these changes

### CODE REVIEW

**Comment by lidavidm** [comment]
Hmm, this might be different because of local vs online matches (at least for the username parsing). Not sure why the additional decode is needed, either; we're already in Python 3. Where are you getting replays to train on?

**Comment by lidavidm** [comment]
Actually, looks like you're getting them online. I'll take a look...

**Comment by djbyrne** [comment]
Hi, I have tried getting them online, using the replays generated by my own bot locally and the CLI tool kit provided by Halite. All of them seem to have the same issue.

**Comment by snaar** [comment]
Should we add version check instead? Given #134.

**Comment by lidavidm** [comment]
Yeah, especially given the server environment is also 3.6.

**Comment by snaar** [comment]
Opened #163 to add version check instead.

**Pull request closed without merging**
